# This file was generated by the {rix} R package v0.18.1 on 2026-04-26
# with following call:
# >rix(r_ver = "4.5.3",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
#
# MANUAL PATCH (2026-04-26):
# 1. Override udunits with -std=gnu89 to fix Apple Silicon Clang rejection
#    of K&R C function definitions in unitcore.c.
# 2. Add shellHook to rebuild R_LIBS_SITE from derivation closure, preventing
#    ABI mismatch segfaults when entering this shell from inside another nix-shell.
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-04-22.tar.gz") {
   overlays = [
     (final: prev: {
       udunits = prev.udunits.overrideAttrs (old: {
         NIX_CFLAGS_COMPILE = (old.NIX_CFLAGS_COMPILE or "") + " -std=gnu89";
       });
     })
   ];
 };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      covr
      devtools
      dplyr
      gert
      giscoR
      igraph
      knitr
      leaflet
      osmdata
      pkgdown
      quarto
      rlang
      rmarkdown
      roxygen2
      sf
      sfdep
      tarchetypes
      targets
      testthat;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      gdal
      geos
      glibcLocales
      nix
      proj
      quarto
      R
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];

    shellHook = ''
      R_LIBS_SITE=""
      for pkg in $buildInputs; do
        for dep in $(nix-store -qR "$pkg" 2>/dev/null); do
          if [ -d "$dep/library" ]; then
            case ":$R_LIBS_SITE:" in
              *":$dep/library:"*) ;;
              *) R_LIBS_SITE="''${R_LIBS_SITE:+$R_LIBS_SITE:}$dep/library" ;;
            esac
          fi
        done
      done
      export R_LIBS_SITE
      unset R_LIBS_USER
      unset R_LIBS
    '';
    
  }; 
in
  {
    inherit pkgs shell;
  }
